// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhmCalcNew.Services.DataAccess;

#nullable disable

namespace WhmCalcNew.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240828111534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WhmCalcNew.Models.TargetUnit", b =>
                {
                    b.Property<string>("UnitName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Save")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Toughness")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Wounds")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.HasKey("UnitName");

                    b.ToTable("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
